version: '3.8'

services:
  db:
    image: mongo:7.0.5  # Update to MongoDB 7.0.5
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./data/dump:/dump  # Ensure this is correct for your use case

  app:
    build: .
    image: 192.168.33.10:8083/nodemongoapp:6.0
    container_name: back
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - mongo-data:/app  # This will mount the volume to the app container

volumes:
  mongo-data:  # Ensure the volume is defined
