name: Full Stack MERN CI/CD Pipeline with Auto Merge

on:
  push:
    branches:
      - main  # Change this to your working branch if different

jobs:
  build-test-merge:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install and test Backend
      - name: Install and test Backend
        working-directory: ./backend
        run: |
          npm install
          npm test  # Run backend tests (if you have them)

      # Step 4: Install and test Frontend
      - name: Install and test Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm test  # Run frontend tests (if you have them)

      # Step 5: Build React Frontend (This is production build, not dev server)
      - name: Build React Frontend
        working-directory: ./frontend
        run: npm run build  # Use build instead of dev

      # Step 6: Build Backend (If applicable, else skip this step)
      - name: Build Backend
        working-directory: ./backend
        run: npm run build  # Use if you have a build step for backend

      # Step 7: Auto merge if all tests and builds pass
      - name: Auto-merge if tests pass
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git pull origin main --rebase
          git push origin main
